project:
  type: website
  
website: 
  title: "Statistical Computing Practicals 2026 (HPTDON002)"
  sidebar: 
    border: true
    background: light
    position: right
    contents:
      - section: "Assignment 1"
        contents:
          - text: "Practical Day 1"
            file: index.qmd
          - text: "Practical Day 3"
            file: prac3.qmd
          - text: "Practical Day 4"
            file: prac4.qmd
            
      - section: "Assignment 2"
        contents:
          - text: "Practical Day 12"
            file: prac10.qmd

format:
  html: 
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false